### ISSUE TITLE
Possibly ignore or handle errors thrown by youtube-dl

### ISSUE THREAD

**Issue by andwn** [bdero/vimash#2]
rip

[youtube] 3OGwfDCTEwk: Downloading webpage
[youtube] 3OGwfDCTEwk: Downloading video info webpage
ERROR: 3OGwfDCTEwk: YouTube said: This video has been removed as a violation of YouTube's policy against spam, scams, and commercially deceptive content.
Traceback (most recent call last):
  File "vimash.py", line 216, in <module>
    youtube_download(sample_videos, cache=config['cache'])
  File "vimash.py", line 100, in youtube_download
    result = ydl.download(videos)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1501, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 669, in extract_info
    self.report_error(compat_str(de), de.format_traceback())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 529, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 499, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: 3OGwfDCTEwk: YouTube said: This video has been removed as a violation of YouTube's policy against spam, scams, and commercially deceptive content.

**Comment by bdero** [comment]
This happens because Youtube doesn't immediately omit removed videos from the search index. I think this should be initially handled by:
- Adding a (configurable) retry limit defaulting to 4 or 5
- Displaying the DownloadError message from YoutubeDL as a warning log
- Omitting the video from the list and moving on

Later on, a more complex behavior could be introduced, like sampling the search results again for another video. One case that will need to be handled here arises when there are no more unique videos to sample, as would happen immediately when `num_videos == max_search`. Since there are no more videos to sample in that case, the video should just gracefully dropped from the list with a warning log.
